### ISSUE TITLE
pynmrstar installation issues

### ISSUE THREAD

**Issue by eisoab** [uwbmrb/PyNMRSTAR#126]
in a fresh install, (`pip install pynmrstar==3.3.2`) I get the error message below when importing pynmrstar
Any idea what could be the cause? 

Thanks - Eiso

```
Python 3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:27:36) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynmrstar
Traceback (most recent call last):
  File "/software/miniforge3/envs/shine/lib/python3.11/site-packages/pynmrstar/__init__.py", line 15, in <module>
    import cnmrstar
ModuleNotFoundError: No module named 'cnmrstar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/miniforge3/envs/shine/lib/python3.11/site-packages/pynmrstar/__init__.py", line 18, in <module>
    import pynmrstar.cnmrstar as cnmrstar
ModuleNotFoundError: No module named 'pynmrstar.cnmrstar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/software/miniforge3/envs/shine/lib/python3.11/site-packages/pynmrstar/__init__.py", line 23, in <module>
    raise ImportError('Could not import cnmrstar sub-module! Your installation appears to be broken.')
ImportError: Could not import cnmrstar sub-module! Your installation appears to be broken.

```

**Comment by jonwedell** [comment]
Hello - I can reproduce the issue, but I can also confirm that it is resolved in version 3.3.3 and above. As I can't change the existing published 3.3.2 package, please update to version 3.3.3 or 3.3.4. The change log is available here: 

https://pynmrstar.readthedocs.io/en/latest/release-notes.html#id1

Best,
Jon
